# Generated by Django 3.1.5 on 2021-01-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookhouse',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookhouse',
            name='subtitle',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
