# Generated by Django 3.1.5 on 2021-01-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210120_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookhouse',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
